# Generated by Django 6.0.4 on 2026-04-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(choices=[('spring', 'الربيع'), ('summer', 'الصيف'), ('autumn', 'الخريف'), ('winter', 'الشتاء'), ('yearround', 'طوال العام')], default='spring', max_length=20)),
                ('care_tips', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
